# Generated by Django 4.0.3 on 2022-03-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.billingaddress'),
        ),
    ]
